site_name: TechStock
docs_dir: ./docs
site_dir: ./site
repo_url: https://github.com/mdsreq-fga-unb/REQ-2025.2-T02-TechStock
repo_name: REQ-2025.2-T02-TechStock

plugins:
  - search
  - offline

theme:
  name: material
  language: pt-BR
  logo: assets/logo.svg
  favicon: assets/logo.svg
  palette:
    # Paleta para modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo escuro
    # Paleta para modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Mudar para modo claro
  features:
    - navigation.instant
    - navigation.tracking
    - toc.follow
    - navigation.top
    - content.code.copy
    - content.action.edit
    - header.autohide
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Visão do Produto:
    - Cenário atual: visao/cenario.md
    - Solução proposta: visao/solucao.md
    - Estratégias: visao/estrategias.md
    - Engenharia de Requisitos: visao/engenharia-de-requisitos.md
    - Cronograma: visao/cronograma.md
    - Interação com cliente: visao/interacao.md
    - Requisitos de Software: visao/requisitos-de-software.md
    - DoR e DoD: visao/dor-e-dod.md
    - Backlog do Produto: visao/backlog-do-produto.md
    - Lições Aprendidas: visao/licoes.md
    - Referências Bibliográficas: visao/referencias-bibliograficas.md
  - Evidências: evidencias/index.md

  - USM: usm/index.md
  - Protótipos: prototipo/index.md
  - Atas:
    - Sprint Planning: atas/sprint-planning/index.md
    - Sprint Review: atas/sprint-review/index.md
    - Sprint Retrospectiva: atas/sprint-retrospectiva/index.md
  
  - Feedback do Cliente: feedback-cliente/index.md
  
  - Estudo de Caso:
    - USM: estudo-caso/usm/index.md
    - PBB: estudo-caso/pbb/index.md
    - Casos de Uso: estudo-caso/casos-de-uso/index.md

  - Cellvex - Sistema: cellvex-sistema/index.md
 